enum ColorizeStyles {
  reset(value: '0'),
  bold(value: '1'),
  dark(value: '2'),
  italic(value: '3'),
  underline(value: '4'),
  blink(value: '5'),
  reverse(value: '7'),
  concealed(value: '8'),
  general(value: '39'),
  black(value: '30'),
  red(value: '31'),
  green(value: '32'),
  yellow(value: '33'),
  blue(value: '34'),
  magenta(value: '35'),
  cyan(value: '36'),
  lightGray(value: '37'),
  darkGray(value: '90'),
  lightRed(value: '91'),
  lightGreen(value: '92'),
  lightYellow(value: '93'),
  lightBlue(value: '94'),
  lightMagenta(value: '95'),
  lightCyan(value: '96'),
  white(value: '97'),
  bgDefault(value: '49'),
  bgBlack(value: '40'),
  bgRed(value: '41'),
  bgGreen(value: '42'),
  bgYellow(value: '43'),
  bgBlue(value: '44'),
  bgMagenta(value: '45'),
  bgCyan(value: '46'),
  bgLightGray(value: '47'),
  bgDarkGray(value: '100'),
  bgLightRed(value: '101'),
  bgLightGreen(value: '102'),
  bgLightYellow(value: '103'),
  bgLightBlue(value: '104'),
  bgLightMagenta(value: '105'),
  bgLightCyan(value: '106'),
  bgWhite(value: '107');

  final String value;

  const ColorizeStyles({required this.value});
}
